{{ if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ template "karma.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
{{- with .Values.configMap.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: "{{ .Release.Name }}-config"
data:
{{- with .Values.configMap.aclsConfig }}
  acls.yaml: |
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.configMap.rawConfig }}
  karma.conf: |
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
